name: 'Terraform'
on:
  push:
    branches:
      - devcontiner
      - githubaction
  # pull_request:
  #     branches:
  #     - development

env:
  TF_IN_AUTOMATION: true
  TF_WORKSPACE: -dev
  TF_BACKEND_PATH: dev.tfvars
  TF_VAR_tf_backend_bucket_name: terraform-vpc-state
  
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TERA_FORM}}
          aws-secret-access-key: ${{ secrets.AWS_TERA_FORM }}
          aws-region: "eu-west-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init 
        run: terraform init
          
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
              
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false 
        continue-on-error: true

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false 

      # - name: Terraform destroy
      #   run: terraform destroy -auto-approve -input=false 
