name: snipeit

on:
  push:
    branches: [devcontainer ]
  
jobs:

  build:
    name: CI/CD-snipeit
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: 13.127.203.37
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          whoami
          pwd
           git clone https://github.com/srikanthoggari/Snipe-IT-GitHub-Actions.git
          cd /home/ubuntu/Snipe-IT-GitHub-Actions
          sudo git pull origin 
